// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBranches(arg1) {
  return window['go']['app']['App']['GetBranches'](arg1);
}

export function GetCommits(arg1, arg2) {
  return window['go']['app']['App']['GetCommits'](arg1, arg2);
}

export function GetCurrentBranch(arg1) {
  return window['go']['app']['App']['GetCurrentBranch'](arg1);
}

export function GetRepoInfo(arg1) {
  return window['go']['app']['App']['GetRepoInfo'](arg1);
}

export function OpenFolderDialog() {
  return window['go']['app']['App']['OpenFolderDialog']();
}

export function PushForceWithLease(arg1) {
  return window['go']['app']['App']['PushForceWithLease'](arg1);
}

export function SquashCommits(arg1) {
  return window['go']['app']['App']['SquashCommits'](arg1);
}

export function ValidateRepo(arg1) {
  return window['go']['app']['App']['ValidateRepo'](arg1);
}
