// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {git} from '../models';

export function GetBranches(arg1:string):Promise<Array<git.Branch>>;

export function GetCommits(arg1:string,arg2:number):Promise<Array<git.Commit>>;

export function GetCurrentBranch(arg1:string):Promise<string>;

export function GetRepoInfo(arg1:string):Promise<git.RepoInfo>;

export function OpenFolderDialog():Promise<string>;

export function SquashCommits(arg1:git.SquashRequest):Promise<git.SquashResult>;

export function ValidateRepo(arg1:string):Promise<boolean>;
